@startuml
title Morse Decoder State Machine

[*] -[Dashed]-> Idle
Idle --> KeyDown : Key Down
Dot --> Dash : Timeout
KeyDown --> Idle : Key Up
Dash --> KeyUp : Key Up
KeyDown --> Dot : Timeout
Dot --> KeyUp : KeyUp
WordSpace --> NewLine : Timeout
KeyUp --> CharacterSpace : Timeout
CharacterSpace --> WordSpace : Timeout
CharacterSpace --> KeyDown : Key Down
KeyUp --> KeyDown : Key Down
WordSpace --> KeyDown : Key Down
NewLine -[Dashed]-> Idle

state Idle
state KeyDown : stopTimeout()
state KeyDown : startTimeout(1)
state Dot : startTimeout(2)
state Dot : dispatchEvent(dot)
state Dash : dispatchEvent(dash)
state KeyUp : stopTimeout()
state KeyUp : startTimeout(3)
state CharacterSpace : dispatchEvent(characterSpace)
state CharacterSpace : startTimeout(4)
state WordSpace : dispatchEvent(wordSpace)
state WordSpace : startTimeout(10)
state NewLine : dispatchEvent(newLine)
state NewLine : switch()

@enduml
